# Generated by Django 4.1 on 2022-08-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=2000)),
                (
                    "schema_name",
                    models.CharField(
                        choices=[("erc721", "ERC721"), ("erc1155", "ERC1155")],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
