# Generated by Django 4.1 on 2022-08-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="schema_name",
            field=models.CharField(
                choices=[("erc721", "ERC721"), ("erc1155", "ERC1155")],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contract",
            name="description",
            field=models.TextField(max_length=2000),
        ),
    ]
