# Generated by Django 4.1 on 2022-08-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="token",
            name="usd_price",
            field=models.FloatField(blank=True),
        ),
    ]
