# Generated by Django 4.1 on 2022-08-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderParameteters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offerer", models.CharField(max_length=50)),
                ("zone", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("zoneHash", models.CharField(max_length=50)),
                ("salt", models.CharField(max_length=50)),
                ("conduitKey", models.CharField(max_length=50)),
                ("startTime", models.IntegerField()),
                ("endTime", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature", models.CharField(max_length=50)),
                ("numerator", models.IntegerField()),
                ("denominator", models.IntegerField()),
                ("extraData", models.CharField(max_length=50)),
                (
                    "parameters",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_orders.orderparameteters",
                    ),
                ),
            ],
        ),
    ]
