# Generated by Django 4.1 on 2022-08-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offerer", models.CharField(max_length=200)),
                ("zone", models.CharField(max_length=200)),
                ("zoneHash", models.CharField(max_length=200)),
                ("startTime", models.CharField(max_length=200)),
                ("endTime", models.CharField(max_length=200)),
                ("orderType", models.IntegerField()),
                ("totalOriginalConsiderationItems", models.IntegerField()),
                ("salt", models.CharField(max_length=200)),
                ("conduitKey", models.CharField(max_length=200)),
                ("counter", models.IntegerField()),
                ("signature", models.CharField(max_length=200)),
            ],
        ),
    ]
