# Generated by Django 4.1 on 2022-08-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consideration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itemType",
                    models.IntegerField(
                        choices=[
                            (0, "Native"),
                            (1, "ERC20"),
                            (2, "ERC721"),
                            (3, "ERC1155"),
                            (4, "ERC721 with criteria"),
                            (5, "ERC1155 with criteria"),
                        ]
                    ),
                ),
                ("token", models.CharField(max_length=50)),
                ("identifierOrCriteria", models.CharField(max_length=50)),
                ("startAmount", models.IntegerField()),
                ("endAmount", models.IntegerField()),
                ("recipient", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itemType",
                    models.IntegerField(
                        choices=[
                            (0, "Native"),
                            (1, "ERC20"),
                            (2, "ERC721"),
                            (3, "ERC1155"),
                            (4, "ERC721 with criteria"),
                            (5, "ERC1155 with criteria"),
                        ]
                    ),
                ),
                ("token", models.CharField(max_length=50)),
                ("identifierOrCriteria", models.CharField(max_length=50)),
                ("startAmount", models.IntegerField()),
                ("endAmount", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="denominator",
        ),
        migrations.RemoveField(
            model_name="order",
            name="extraData",
        ),
        migrations.RemoveField(
            model_name="order",
            name="numerator",
        ),
        migrations.RemoveField(
            model_name="orderparameteters",
            name="type",
        ),
        migrations.AddField(
            model_name="orderparameteters",
            name="counter",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderparameteters",
            name="orderType",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderparameteters",
            name="totalOriginalConsiderationItems",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderparameteters",
            name="endTime",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="orderparameteters",
            name="startTime",
            field=models.CharField(max_length=50),
        ),
    ]
