# Generated by Django 4.1 on 2022-08-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_orderparameters", "0001_initial"),
        ("api_orders", "0002_consideration_offer_remove_order_denominator_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Consideration",
        ),
        migrations.DeleteModel(
            name="Offer",
        ),
        migrations.AlterField(
            model_name="order",
            name="parameters",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_orderparameters.orderparameters",
            ),
        ),
        migrations.DeleteModel(
            name="OrderParameteters",
        ),
    ]
