# Generated by Django 4.1 on 2022-08-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_orders", "0003_delete_consideration_delete_offer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="signature",
            field=models.CharField(max_length=200),
        ),
    ]
