# Generated by Django 4.1 on 2022-08-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_items", "0002_alter_item_recipient"),
        ("api_orders", "0004_remove_order_consideration_remove_order_offer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="consideration",
        ),
        migrations.RemoveField(
            model_name="order",
            name="offer",
        ),
        migrations.AddField(
            model_name="order",
            name="consideration",
            field=models.ManyToManyField(
                null=True, related_name="consideration", to="api_items.item"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="offer",
            field=models.ManyToManyField(
                null=True, related_name="offer", to="api_items.item"
            ),
        ),
    ]
