# Generated by Django 4.1 on 2022-08-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_orderparameters", "0001_initial"),
        ("api_orders", "0007_remove_order_consideration_remove_order_offer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="conduitKey",
        ),
        migrations.RemoveField(
            model_name="order",
            name="consideration",
        ),
        migrations.RemoveField(
            model_name="order",
            name="counter",
        ),
        migrations.RemoveField(
            model_name="order",
            name="endTime",
        ),
        migrations.RemoveField(
            model_name="order",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="offerer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="orderType",
        ),
        migrations.RemoveField(
            model_name="order",
            name="salt",
        ),
        migrations.RemoveField(
            model_name="order",
            name="startTime",
        ),
        migrations.RemoveField(
            model_name="order",
            name="totalOriginalConsiderationItems",
        ),
        migrations.RemoveField(
            model_name="order",
            name="zone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="zoneHash",
        ),
        migrations.AddField(
            model_name="order",
            name="parameters",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_orderparameters.orderparameter",
            ),
        ),
    ]
