# Generated by Django 4.1 on 2022-08-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_users", "0001_initial"),
        ("api_assets", "0001_initial"),
        ("api_tokens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("succesfull", "Succesfull"),
                            ("cancelled", "Cancelled"),
                            ("bid_entered", "Bid entered"),
                            ("bid_withdrawn", "Bid withdrawn"),
                            ("transfer", "Transfer"),
                            ("offer_entered", "Offer entered"),
                            ("approve", "Approve"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_time", models.CharField(max_length=100)),
                ("end_time", models.CharField(max_length=100)),
                ("start_amount", models.CharField(max_length=100)),
                ("end_amount", models.CharField(max_length=100)),
                ("is_private", models.BooleanField(default=False)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_assets.asset",
                    ),
                ),
                (
                    "from_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_account",
                        to="api_users.user",
                    ),
                ),
                (
                    "payment_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_tokens.token",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="to_account",
                        to="api_users.user",
                    ),
                ),
            ],
        ),
    ]
