# Generated by Django 4.1 on 2022-08-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="timestamp",
            new_name="created_timestamp",
        ),
    ]
