# Generated by Django 4.1 on 2022-08-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_events", "0002_rename_timestamp_event_created_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_timestamp",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
