# Generated by Django 4.1 on 2022-08-14 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_assets", "0005_remove_asset_last_sale_alter_asset_description"),
        ("api_tokens", "0002_alter_token_name_alter_token_usd_price"),
        ("api_users", "0002_alter_user_config"),
        ("api_events", "0003_alter_event_created_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="from_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_account",
                to="api_users.user",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="payment_token",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_tokens.token",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="to_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_account",
                to="api_users.user",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="total_price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
