# Generated by Django 4.1 on 2022-08-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0002_alter_user_config"),
        ("api_events", "0004_event_asset_event_from_account_event_is_private_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="to_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_account",
                to="api_users.user",
            ),
        ),
    ]
