# Generated by Django 4.1 on 2022-08-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_events", "0005_alter_event_to_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[("created", "Created"), ("succesfull", "Succesfull")],
                max_length=50,
            ),
        ),
    ]
