# Generated by Django 4.1 on 2022-08-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_events", "0006_alter_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("succesfull", "Succesfull"),
                    ("cancelled", "Cancelled"),
                    ("bid_entered", "Bid entered"),
                    ("bid_withdrawn", "Bid withdrawn"),
                    ("transfer", "Transfer"),
                    ("offer_entered", "Offer entered"),
                    ("approve", "Approve"),
                ],
                max_length=50,
            ),
        ),
    ]
