# Generated by Django 4.1 on 2022-08-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_contracts", "0001_initial"),
        ("api_users", "0001_initial"),
        ("api_collections", "0001_initial"),
        ("api_orders", "0001_initial"),
        ("api_tokens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("image_url", models.URLField(blank=True)),
                ("external_link", models.URLField(blank=True)),
                ("transfer_fee", models.IntegerField(default=0)),
                ("is_nsfw", models.BooleanField(default=False)),
                ("listing_date", models.DateTimeField(blank=True, null=True)),
                (
                    "asset_contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_contracts.contract",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_collections.collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator",
                        to="api_users.user",
                    ),
                ),
                (
                    "orders",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_orders.order",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner",
                        to="api_users.user",
                    ),
                ),
                (
                    "transfer_fee_payment_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_tokens.token",
                    ),
                ),
            ],
        ),
    ]
