# Generated by Django 4.1 on 2022-08-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_tokens", "0002_alter_token_name_alter_token_usd_price"),
        ("api_orders", "0001_initial"),
        ("api_events", "0002_rename_timestamp_event_created_timestamp"),
        ("api_users", "0002_alter_user_config"),
        ("api_assets", "0002_asset_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator",
                to="api_users.user",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="external_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_nsfw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="asset",
            name="last_sale",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_events.event",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="orders",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_orders.order",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="transfer_fee",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="transfer_fee_payment_token",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_tokens.token",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="api_users.user",
            ),
        ),
    ]
