# Generated by Django 4.1 on 2022-08-11 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_orders", "0001_initial"),
        ("api_events", "0003_alter_event_created_timestamp"),
        ("api_tokens", "0002_alter_token_name_alter_token_usd_price"),
        (
            "api_assets",
            "0003_asset_creator_asset_external_link_asset_image_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="last_sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_events.event",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="orders",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="transfer_fee_payment_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_tokens.token",
            ),
        ),
    ]
