# Generated by Django 4.1 on 2022-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_assets", "0005_remove_asset_last_sale_alter_asset_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="listing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
