# Generated by Django 4.1 on 2022-08-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_tokens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_created=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=20000)),
                ("slug", models.CharField(max_length=50)),
                ("banner_image_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                ("twitter_username", models.CharField(blank=True, max_length=50)),
                ("instagram_username", models.CharField(blank=True, max_length=50)),
                ("medium_username", models.CharField(blank=True, max_length=50)),
                ("is_nsfw", models.BooleanField(default=False)),
                (
                    "payment_tokens",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_tokens.token",
                    ),
                ),
            ],
        ),
    ]
