# Generated by Django 4.1 on 2022-08-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_tokens", "0001_initial"),
        ("api_collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="banner_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="created_timestamp",
            field=models.DateTimeField(default="2022-08-06T09:54:58Z"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collection",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="instagram_username",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="collection",
            name="is_nsfw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collection",
            name="medium_username",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="collection",
            name="payment_tokens",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_tokens.token",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="twitter_username",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
