# Generated by Django 4.1 on 2022-08-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_collections", "0002_collection_banner_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="created_timestamp",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
