# Generated by Django 4.1 on 2022-08-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_hash", models.CharField(max_length=50)),
                ("block_number", models.CharField(max_length=50)),
                ("hash", models.CharField(max_length=50)),
                ("index", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                (
                    "from_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_users.user",
                    ),
                ),
            ],
        ),
    ]
