# Generated by Django 4.1 on 2022-08-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_hash", models.CharField(max_length=50)),
                ("block_number", models.CharField(max_length=50)),
                ("hash", models.CharField(max_length=50)),
                ("index", models.CharField(max_length=50)),
                ("created_timestamp", models.DateTimeField()),
            ],
        ),
    ]
