# Generated by Django 4.1 on 2022-08-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_transactions", "0002_transaction_to_account_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="timestamp",
            new_name="created_timestamp",
        ),
    ]
