# Generated by Django 4.1 on 2022-08-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_transactions", "0003_rename_timestamp_transaction_created_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="from_account",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="to_account",
        ),
    ]
