# Generated by Django 4.1 on 2022-08-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_orderconsiderations", "0001_initial"),
        ("api_orderoffers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offerer", models.CharField(max_length=200)),
                ("zone", models.CharField(max_length=200)),
                ("zoneHash", models.CharField(max_length=200)),
                ("startTime", models.CharField(max_length=200)),
                ("endTime", models.CharField(max_length=200)),
                ("orderType", models.IntegerField()),
                ("totalOriginalConsiderationItems", models.IntegerField()),
                ("salt", models.CharField(max_length=200)),
                ("conduitKey", models.CharField(max_length=200)),
                ("counter", models.IntegerField()),
                (
                    "consideration",
                    models.ManyToManyField(
                        null=True, to="api_orderconsiderations.orderconsideration"
                    ),
                ),
                (
                    "offer",
                    models.ManyToManyField(null=True, to="api_orderoffers.orderoffer"),
                ),
            ],
        ),
    ]
