# Generated by Django 4.1 on 2022-08-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_items", "0002_alter_item_recipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offerer", models.CharField(max_length=200)),
                ("zone", models.CharField(max_length=200)),
                ("zoneHash", models.CharField(max_length=200)),
                ("startTime", models.CharField(max_length=200)),
                ("endTime", models.CharField(max_length=200)),
                ("orderType", models.IntegerField()),
                ("totalOriginalConsiderationItems", models.IntegerField()),
                ("salt", models.CharField(max_length=200)),
                ("conduitKey", models.CharField(max_length=200)),
                ("counter", models.IntegerField()),
                (
                    "consideration",
                    models.ManyToManyField(
                        null=True, related_name="consideration", to="api_items.item"
                    ),
                ),
                (
                    "offer",
                    models.ManyToManyField(
                        null=True, related_name="offer", to="api_items.item"
                    ),
                ),
            ],
        ),
    ]
