# Generated by Django 4.1 on 2022-08-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("profile_img_url", models.URLField(blank=True)),
                ("config", models.CharField(max_length=100)),
            ],
        ),
    ]
