# Generated by Django 4.1 on 2022-08-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="config",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
