# Generated by Django 4.1 on 2022-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0002_alter_user_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="config",
            field=models.CharField(
                blank=True,
                choices=[("verified", "Verified"), ("moderator", "Moderator")],
                max_length=100,
            ),
        ),
    ]
