# Generated by Django 4.1 on 2022-08-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itemType",
                    models.IntegerField(
                        choices=[
                            (0, "Native"),
                            (1, "ERC20"),
                            (2, "ERC721"),
                            (3, "ERC1155"),
                            (4, "ERC721 with criteria"),
                            (5, "ERC1155 with criteria"),
                        ]
                    ),
                ),
                ("token", models.CharField(max_length=200)),
                ("identifierOrCriteria", models.CharField(max_length=200)),
                ("startAmount", models.IntegerField()),
                ("endAmount", models.IntegerField()),
                ("recipient", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
