# Generated by Django 4.1 on 2022-08-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField()),
                ("token", models.CharField(max_length=50)),
                ("identifierOrCriteria", models.CharField(max_length=50)),
                ("startAmount", models.IntegerField()),
                ("endAmount", models.IntegerField()),
                ("recipient", models.CharField(max_length=50)),
            ],
        ),
    ]
