# Generated by Django 4.1 on 2022-08-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="recipient",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
